server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oficina_db
    username: postgres
    password: 3782
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: "osmech-secret-key-change-in-production-min-256-bits-long-for-hs256"
  expiration: 86400000  # 24 hours in milliseconds

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "Authorization,Content-Type"

# Configurações para integração com OpenAI
openai:
  api:
    key: "sua-chave-aqui"
    url: "https://api.openai.com/v1/completions"

